const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const APP_REV="REV_07";
const SCHEMA_VERSION=7;
const STORAGE_KEY="hide_seek_state";
const SESSION_API_KEY="hide_seek_runtime_api_key";
const ASSET_DB_NAME="hide-seek-assets";
const DEFAULT_WORDS=[
{id:"w1",eng:"environment",kor:"환경",example:"We should protect the environment.",wrong:2,pass:0,hint:0,learningStats:{}},
{id:"w2",eng:"evidence",kor:"증거",example:"We found new evidence.",wrong:2,pass:0,hint:0,learningStats:{}},
{id:"w3",eng:"responsible",kor:"책임이 있는",example:"She is responsible for the task.",wrong:2,pass:0,hint:0,learningStats:{}},
{id:"w4",eng:"maintain",kor:"유지하다",example:"It is hard to maintain focus.",wrong:1,pass:0,hint:0,learningStats:{}},
{id:"w5",eng:"present",kor:"현재의",example:"Focus on the present moment.",wrong:0,pass:0,hint:0,learningStats:{}},
{id:"w6",eng:"essential",kor:"필수적인",example:"Sleep is essential for health.",wrong:2,pass:0,hint:0,learningStats:{}},
{id:"w7",eng:"approach",kor:"접근하다",example:"We need a new approach.",wrong:0,pass:0,hint:0,learningStats:{}},
{id:"w8",eng:"challenge",kor:"도전",example:"This word is a good challenge.",wrong:0,pass:0,hint:0,learningStats:{}},
{id:"w9",eng:"consider",kor:"고려하다",example:"Consider every clue.",wrong:0,pass:0,hint:0,learningStats:{}},
{id:"w10",eng:"benefit",kor:"이익, 혜택",example:"Practice has many benefits.",wrong:0,pass:0,hint:0,learningStats:{}}
];
const GUIDE_OPTIONS=[
{id:"fox",label:"호기심 많은 여우",img:"./assets/characters/guide_default.png",style:"curious",tone:"궁금한 친구"},
{id:"rabbit",label:"느긋한 토끼",img:"./assets/characters/rabbit.png",style:"calm",tone:"느긋한 친구"},
{id:"raccoon",label:"장난 많은 친구",img:"./assets/characters/sloth.png",style:"play",tone:"장난 많은 친구"},
{id:"cat",label:"은근히 시크한 친구",img:"./assets/characters/fennec.png",style:"chic",tone:"은근히 시크한 친구"}
];
const NAME_BANK=["포레","루나","모카","리오","코코","민트","클로버","아루","루미","가온","토리","라온"];
const nowISO=()=>new Date().toISOString();
const today=()=>nowISO().slice(0,10);
const clone=x=>JSON.parse(JSON.stringify(x));
const DEFAULT_STATE={
 schemaVersion:SCHEMA_VERSION,appRevision:APP_REV,
 profile:{displayName:"",avatarMode:"default",avatarAssetRef:"",createdAt:"",updatedAt:""},
 guide:{id:"fox",name:"",style:"curious",voice:true},
 settings:{sound:true,partnerVoice:true,reducedMotion:false,pressureReduced:false,geminiModel:"gemini-2.5-flash"},
 sheets:[{sheetId:"sample",title:"이번 주 시험",createdAt:nowISO(),updatedAt:nowISO(),testDate:"",sourceType:"sample",sourceCount:0,status:"LEARNING",caseMastery:0,items:clone(DEFAULT_WORDS),recognitionMeta:{}}],
 activeSheetId:"sample",sessions:[],xp:0,streak:0,lastStudy:"",memory:{},lexicon:{},memoryEvents:{shownBySheet:{},lastLexicalId:""},ocrDraft:null,
 captureSession:null,
 learning:{phase:"first",firstIndex:0,meaningIndex:0,connectionRound:0,weakRound:0,combo:0,flow:0,fever:false,history:[]},
 codeRed:{index:0,results:{},history:[],retrace:[],retryOnly:false,targetIds:[]},
 onboardingStep:0,onboardingDone:false
};
function senseKey(w){return `${String(w?.eng||"").trim().toLowerCase()}::${String(w?.kor||"").trim().replace(/\s+/g," ")}`}
function normalizeWord(w,i=0){const eng=String(w.eng||"").trim(),kor=String(w.kor||"").trim();return {id:w.id||`w-${Date.now()}-${i}`,lexicalId:w.lexicalId||senseKey({eng,kor}),eng,kor,example:w.example||"",wrong:Number(w.wrong||0),pass:Number(w.pass||0),hint:Number(w.hint||0),confidence:w.confidence||"high",needsReview:!!w.needsReview,manuallyEdited:!!w.manuallyEdited,reviewConfirmed:!!w.reviewConfirmed,sourcePageId:w.sourcePageId||"",learningStats:w.learningStats||{}}}
function migrate(raw){
 const s=Object.assign(clone(DEFAULT_STATE),raw||{});
 s.schemaVersion=SCHEMA_VERSION;s.appRevision=APP_REV;
 s.profile=Object.assign({},DEFAULT_STATE.profile,raw?.profile||{});s.guide=Object.assign({},DEFAULT_STATE.guide,raw?.guide||{});s.settings=Object.assign({},DEFAULT_STATE.settings,raw?.settings||{});
 s.learning=Object.assign({},DEFAULT_STATE.learning,raw?.learning||raw?.study||{});s.codeRed=Object.assign({},DEFAULT_STATE.codeRed,raw?.codeRed||{});s.memory=raw?.memory||{};s.lexicon=raw?.lexicon||{};s.memoryEvents=Object.assign({},DEFAULT_STATE.memoryEvents,raw?.memoryEvents||{});s.memoryEvents.shownBySheet=s.memoryEvents.shownBySheet||{};
 if(!Array.isArray(s.sheets)||!s.sheets.length)s.sheets=clone(DEFAULT_STATE.sheets);
 s.sheets=s.sheets.map((sh,si)=>({...sh,sheetId:sh.sheetId||`sheet-${si}`,updatedAt:sh.updatedAt||sh.createdAt||nowISO(),status:sh.status||"READY",caseMastery:Number(sh.caseMastery||0),items:(sh.items||[]).map(normalizeWord),recognitionMeta:sh.recognitionMeta||{},learningProvenance:sh.learningProvenance||{}}));
 if(!s.sheets.find(x=>x.sheetId===s.activeSheetId))s.activeSheetId=s.sheets[0].sheetId;
 return s;
}
function isCompatibleLegacyState(v){
 return !!(v&&typeof v==="object"&&Array.isArray(v.sheets)&&v.sheets.some(sh=>Array.isArray(sh?.items)&&sh.items.some(w=>w&&("eng" in w||"kor" in w)))&&(v.profile||v.guide||v.memory||v.codeRed));
}
function discoverCompatibleLegacyState(){
 try{
  for(let i=0;i<localStorage.length;i++){
   const key=localStorage.key(i);
   if(!key||key===STORAGE_KEY)continue;
   try{const parsed=JSON.parse(localStorage.getItem(key));if(isCompatibleLegacyState(parsed))return parsed}catch{}
  }
 }catch{}
 return null;
}
function load(){
 try{
  const current=localStorage.getItem(STORAGE_KEY);
  if(current)return migrate(JSON.parse(current));
  const legacy=discoverCompatibleLegacyState();
  if(legacy){
   const migrated=migrate(legacy);
   localStorage.setItem(STORAGE_KEY,JSON.stringify(migrated));
   return migrated;
  }
  return clone(DEFAULT_STATE);
 }catch{return clone(DEFAULT_STATE)}
}
let S=load(),currentTab="home",viewStack=[],runtimeApiKey=sessionStorage.getItem(SESSION_API_KEY)||"",selectedGuide=S.guide.id||"fox",selectedGuideName=S.guide.name||"",selectedProfileFile=null,selectedTile=null,codeSession=null,codeTimer=null,selectedKey=null,toastTimer=null;
function save(){S.schemaVersion=SCHEMA_VERSION;S.appRevision=APP_REV;localStorage.setItem(STORAGE_KEY,JSON.stringify(S))}
function sheet(){return S.sheets.find(x=>x.sheetId===S.activeSheetId)||S.sheets[0]}
function validWords(){return (sheet()?.items||[]).filter(w=>w.eng&&w.kor&&!w.needsReview)}
function allWords(){return sheet()?.items||[]}
function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function shuffle(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function toast(msg){const t=$("#toast");if(!t)return;t.textContent=msg;t.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove("show"),1900)}
function guideAsset(mood="default"){const m={default:"guide_default",smile:"guide_smile",think:"guide_think",play:"guide_play",focus:"guide_focus",cheer:"guide_cheer",hint:"guide_hint",note:"guide_note",radio:"guide_radio",fever:"guide_fever"}[mood]||"guide_default";return `./assets/characters/${m}.png`}
function setPartner(msg,mood="default",speakIt=false){const text=$("#partnerText"),name=$("#partnerName"),img=$("#partnerAvatar");if(text)text.textContent=msg;if(name)name.textContent=S.guide.name||"나의 길잡이";if(img)img.src=guideAsset(mood);if(speakIt)partnerSpeak(msg)}
function partnerSpeak(text=$("#partnerText")?.textContent||""){if(!S.settings.partnerVoice||!S.guide.voice||!("speechSynthesis" in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="ko-KR";u.rate=.96;speechSynthesis.speak(u)}
function speakWord(word){if(!("speechSynthesis" in window))return toast("이 기기에서는 음성 기능을 사용할 수 없어요.");speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(word);u.lang="en-US";u.rate=.82;speechSynthesis.speak(u)}
function markStudy(xp=2){const d=today();if(S.lastStudy!==d){S.streak=S.lastStudy?S.streak+1:1;S.lastStudy=d;S.sessions.push({date:d,count:0})}const r=S.sessions.find(x=>x.date===d);if(r)r.count++;S.xp+=xp;save()}
function lexiconEntry(w){return S.lexicon?.[w?.lexicalId||senseKey(w)]||null}
function memoryStrength(){const ws=validWords();if(!ws.length)return 0;const measured=ws.map(w=>lexiconEntry(w)?.memoryStrength).filter(v=>Number.isFinite(v));if(!measured.length)return 0;return Math.round(measured.reduce((a,v)=>a+v,0)/measured.length)}
function syncSheetToLexicon(sh=sheet()){if(!sh)return;S.lexicon=S.lexicon||{};for(const w of (sh.items||[]).filter(x=>x.eng&&x.kor&&!x.needsReview)){const key=w.lexicalId||senseKey(w),prev=S.lexicon[key]||{},attempts=(S.codeRed.history||[]).filter(a=>a.wordId===w.id),correct=attempts.filter(a=>["CORRECT","SLOW_CORRECT"].includes(a.type)).length,wrong=attempts.filter(a=>["WRONG","PASS","TIMEOUT","HINT_USED"].includes(a.type)).length,lastWrong=[...attempts].reverse().find(a=>["WRONG","PASS","TIMEOUT","HINT_USED"].includes(a.type))?.at||prev.lastWrong||null,sourceRefs=[...new Set([...(prev.sourceRefs||[]),sh.sheetId])],base=Number.isFinite(prev.memoryStrength)?prev.memoryStrength:60,delta=Math.min(18,correct*4)-Math.min(28,wrong*6),memory=Math.max(10,Math.min(100,base+delta)),priority=Math.max(0,100-memory+wrong*8+(w.learningStats?.timeout||0)*5+(w.learningStats?.slowCorrect||0)*2);S.lexicon[key]={lexicalId:key,canonicalSpelling:w.eng.toLowerCase(),sense:w.kor,firstSeen:prev.firstSeen||sh.createdAt||nowISO(),lastSeen:nowISO(),sourceRefs,correctTotal:Number(prev.correctTotal||0)+correct,wrongTotal:Number(prev.wrongTotal||0)+wrong,consecutiveCorrect:wrong?0:Number(prev.consecutiveCorrect||0)+correct,lastWrong,memoryStrength:memory,nextReviewPriority:priority}}}
function selectPastMemoryEvent(){const active=sheet()?.sheetId;if(!active||S.memoryEvents?.shownBySheet?.[active])return null;const pool=Object.values(S.lexicon||{}).filter(x=>(x.sourceRefs||[]).some(id=>id!==active)).sort((a,b)=>(b.nextReviewPriority||0)-(a.nextReviewPriority||0));if(!pool.length)return null;return pool.find(x=>x.lexicalId!==S.memoryEvents?.lastLexicalId)||pool[0]}
function markMemoryEventShown(entry){const active=sheet()?.sheetId;if(!active||!entry)return;S.memoryEvents=S.memoryEvents||{shownBySheet:{},lastLexicalId:""};S.memoryEvents.shownBySheet=S.memoryEvents.shownBySheet||{};S.memoryEvents.shownBySheet[active]={lexicalId:entry.lexicalId,shownAt:nowISO()};S.memoryEvents.lastLexicalId=entry.lexicalId;save()}
function learningProgress(){const ws=validWords();if(!ws.length)return 0;const p={first:15,meaning:42,connection:68,weak:82,code:90,done:100}[S.learning.phase]||0;return p}
function stateLabel(st){return ({DRAFT:"초안",REVIEW_REQUIRED:"확인 필요",READY:"학습 준비",LEARNING:"학습 중",CODE_RED_READY:"FINAL SEEK 준비",RETRACE_REQUIRED:"다시 찾기",TEST_READY:"시험 준비 완료",COMPLETED:"완료",ARCHIVED:"보관"})[st]||st}
function weakScore(w){return (w.wrong||0)*5+(w.pass||0)*4+(w.hint||0)*3+(w.learningStats?.timeout||0)*4+(w.learningStats?.slowCorrect||0)*2}
function updateChrome(){const onboard=!S.onboardingDone;$("#bottomNav").style.display=onboard?"none":"grid";$("#partnerBar").style.display=onboard?"none":"flex";$("#settingsBtn").style.visibility=onboard?"hidden":"visible";$("#backBtn").hidden=viewStack.length===0;$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.tab===currentTab))}
function pushView(fn){viewStack.push(()=>render());fn();updateChrome()}
function goBack(){const fn=viewStack.pop();stopCodeTimer();if(fn)fn();else render();updateChrome()}
function render(){stopCodeTimer();updateChrome();if(!S.onboardingDone)return renderOnboarding();const map={home:renderHome,sheets:renderSheets,study:renderLearningHub,words:renderWords,records:renderRecords};(map[currentTab]||renderHome)();updateChrome()}
async function dbOpen(name=ASSET_DB_NAME){return new Promise((res,rej)=>{const q=indexedDB.open(name,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains("assets"))q.result.createObjectStore("assets")};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function dbSet(k,v){const db=await dbOpen();return new Promise((res,rej)=>{const tx=db.transaction("assets","readwrite");tx.objectStore("assets").put(v,k);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function dbDel(k){const db=await dbOpen();return new Promise((res,rej)=>{const tx=db.transaction("assets","readwrite");tx.objectStore("assets").delete(k);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function readAssetFromDb(db,k){return new Promise((res,rej)=>{if(!db.objectStoreNames.contains("assets"))return res(undefined);const q=db.transaction("assets").objectStore("assets").get(k);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function discoverCompatibleLegacyAsset(k){
 if(typeof indexedDB.databases!=="function")return undefined;
 try{
  const dbs=await indexedDB.databases();
  for(const meta of dbs){
   if(!meta?.name||meta.name===ASSET_DB_NAME)continue;
   try{
    const db=await new Promise((res,rej)=>{const q=indexedDB.open(meta.name);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)});
    const value=await readAssetFromDb(db,k);
    db.close();
    if(value!==undefined){await dbSet(k,value);return value}
   }catch{}
  }
 }catch{}
 return undefined;
}
async function dbGet(k){const db=await dbOpen();const value=await readAssetFromDb(db,k);if(value!==undefined)return value;return discoverCompatibleLegacyAsset(k)}
async function avatarURL(){if(S.profile.avatarMode!=="illustrated")return "";try{const blob=await dbGet("profile-avatar");return blob?URL.createObjectURL(blob):""}catch{return ""}}
async function stylizePhoto(file){const bmp=await createImageBitmap(file,{imageOrientation:"from-image"});const low=256,size=512,c=document.createElement("canvas"),small=document.createElement("canvas");small.width=low;small.height=low;const sctx=small.getContext("2d",{willReadFrequently:true}),scale=Math.max(low/bmp.width,low/bmp.height),w=bmp.width*scale,h=bmp.height*scale;sctx.filter="saturate(1.16) contrast(1.06) brightness(1.05)";sctx.drawImage(bmp,(low-w)/2,(low-h)/2,w,h);const data=sctx.getImageData(0,0,low,low),px=data.data,step=34;for(let i=0;i<px.length;i+=4){px[i]=Math.round(px[i]/step)*step;px[i+1]=Math.round(px[i+1]/step)*step;px[i+2]=Math.round(px[i+2]/step)*step}sctx.putImageData(data,0,0);c.width=size;c.height=size;const ctx=c.getContext("2d");ctx.imageSmoothingQuality="high";ctx.drawImage(small,0,0,size,size);ctx.globalCompositeOperation="soft-light";ctx.fillStyle="rgba(184,220,164,.22)";ctx.fillRect(0,0,size,size);ctx.globalCompositeOperation="source-over";return new Promise(r=>c.toBlob(r,"image/webp",.9))}
function renderOnboarding(){
 const step=S.onboardingStep||0,dots=`<div class="step-dots">${[0,1,2,3].map(i=>`<i class="${i<=step?"on":""}"></i>`).join("")}</div>`;
 if(step===0)$("#view").innerHTML=`<section class="onboard"><div class="onboard-head">${dots}<h1>탐험가, 반가워!</h1><p>사용자와 길잡이는 서로 다른 존재야. 먼저 네 이름부터 정해볼까?</p></div><section class="card tint-leaf"><label>사용자 이름</label><input id="profileName" class="input" maxlength="20" value="${esc(S.profile.displayName)}" placeholder="이름을 입력해 주세요"><div class="section-title"><h2>빠른 선택</h2><span>언제든 변경 가능</span></div><div class="name-chip-row">${["지우","서윤","도윤","예준"].map(n=>`<button class="name-chip" data-profile-name="${n}" type="button">${n}</button>`).join("")}</div><div class="btn-row" style="margin-top:16px"><button class="btn secondary" data-skip-all type="button">나중에 하기</button><button class="btn primary" id="nextProfileName" type="button">다음</button></div></section></section>`;
 if(step===1)$("#view").innerHTML=`<section class="onboard"><div class="onboard-head">${dots}<h1>내 Hide & Seek 프로필</h1><p>사진은 선택 사항이야. 원본은 장기 저장하지 않아.</p></div><section class="card tint-sky"><div class="photo-preview" id="photoPreview"><span>사진 선택</span></div><div class="btn-row"><button class="btn secondary" id="profileCameraBtn" type="button">사진 찍기</button><button class="btn secondary" id="profileLibraryBtn" type="button">앨범에서 선택</button></div><p style="margin-top:11px">선택한 이미지는 기기 안에서 프로필용 톤으로 변환하며, 확정 결과만 IndexedDB에 저장합니다.</p><div class="btn-row" style="margin-top:16px"><button class="btn secondary" data-next="2" type="button">나중에 하기</button><button class="btn primary" id="confirmAvatar" type="button">계속</button></div></section></section>`;
 if(step===2)$("#view").innerHTML=`<section class="onboard"><div class="onboard-head">${dots}<h1>나의 길잡이</h1><p>능력은 모두 같아. 취향과 애착만 고르면 돼.</p></div><div class="guide-grid">${GUIDE_OPTIONS.map(g=>`<button class="guide-card ${selectedGuide===g.id?"selected":""}" data-guide="${g.id}" type="button"><img src="${g.img}" alt=""><b>${g.label}</b><small>${g.tone}</small></button>`).join("")}</div><div class="btn-row" style="margin-top:16px"><button class="btn secondary" data-next="3" type="button">나중에 정하기</button><button class="btn primary" data-next="3" type="button">같이 갈래?</button></div></section>`;
 if(step===3)$("#view").innerHTML=`<section class="onboard"><div class="onboard-head">${dots}<h1>이름을 지어줄까?</h1><p>추천받거나 직접 입력할 수 있어.</p></div><section class="card"><div class="partner-mini"><img src="${guideAsset("smile")}" alt=""><div><b>${GUIDE_OPTIONS.find(x=>x.id===selectedGuide)?.label||"나의 길잡이"}</b><p>학습 기능은 어떤 이름을 골라도 같아.</p></div></div><div class="section-title"><h2>이름 추천</h2><button class="btn secondary" id="rerollNames" type="button">다시 추천</button></div><div class="name-chip-row">${shuffle(NAME_BANK).slice(0,5).map(n=>`<button class="name-chip ${selectedGuideName===n?"selected":""}" data-guide-name="${n}" type="button">${n}</button>`).join("")}</div><div class="section-title"><h2>직접 입력</h2></div><input id="guideNameInput" class="input" maxlength="16" value="${esc(selectedGuideName)}" placeholder="길잡이 이름"><div class="btn-row" style="margin-top:16px"><button class="btn secondary" id="finishNoGuideName" type="button">나중에 정하기</button><button class="btn primary" id="finishOnboarding" type="button">동행 시작</button></div></section></section>`;
 bindOnboarding();updateChrome()
}
function bindOnboarding(){
 $$('[data-profile-name]').forEach(b=>b.onclick=()=>{$('#profileName').value=b.dataset.profileName});
 $('#nextProfileName')?.addEventListener('click',()=>{const n=$('#profileName').value.trim();if(!n)return toast('이름을 입력해 주세요.');S.profile.displayName=n;S.profile.updatedAt=nowISO();S.onboardingStep=1;save();render()});
 $('[data-skip-all]')?.addEventListener('click',()=>finishOnboard());$$('[data-next]').forEach(b=>b.onclick=()=>{S.onboardingStep=Number(b.dataset.next);save();render()});
 $('#profileCameraBtn')?.addEventListener('click',()=>$('#profileCameraInput').click());$('#profileLibraryBtn')?.addEventListener('click',()=>$('#profileLibraryInput').click());
 $$('[data-guide]').forEach(b=>b.onclick=()=>{selectedGuide=b.dataset.guide;renderOnboarding()});$('#rerollNames')?.addEventListener('click',()=>{selectedGuideName='';renderOnboarding()});
 $$('[data-guide-name]').forEach(b=>b.onclick=()=>{selectedGuideName=b.dataset.guideName;$('#guideNameInput').value=selectedGuideName;$$('[data-guide-name]').forEach(x=>x.classList.toggle('selected',x===b))});
 $('#finishNoGuideName')?.addEventListener('click',()=>finishOnboard(''));$('#finishOnboarding')?.addEventListener('click',()=>finishOnboard($('#guideNameInput').value.trim()));
 $('#confirmAvatar')?.addEventListener('click',async()=>{if(selectedProfileFile){const blob=await stylizePhoto(selectedProfileFile);await dbSet('profile-avatar',blob);S.profile.avatarMode='illustrated';S.profile.avatarAssetRef='indexeddb:profile-avatar'}S.onboardingStep=2;save();render()});
}
async function profilePicked(file){if(!file||!file.type.startsWith('image/'))return toast('이미지 파일을 선택해 주세요.');selectedProfileFile=file;const blob=await stylizePhoto(file),url=URL.createObjectURL(blob),box=$('#photoPreview');if(box)box.innerHTML=`<img src="${url}" alt="프로필 미리보기">`}
function finishOnboard(name=selectedGuideName){S.guide.id=selectedGuide;S.guide.name=name||'길잡이';S.guide.style=GUIDE_OPTIONS.find(x=>x.id===selectedGuide)?.style||'curious';S.onboardingDone=true;S.onboardingStep=4;S.profile.createdAt=S.profile.createdAt||nowISO();save();currentTab='home';viewStack=[];render();setPartner(`${S.profile.displayName||'탐험가'}, 새 단어가 숨어 있어. 시험지부터 볼까?`,'smile')}
async function renderHome(){
 const av=await avatarURL(),sh=sheet(),ws=validWords(),weak=ws.filter(w=>weakScore(w)>0).length,progress=learningProgress(),remain=Math.max(0,ws.length-Object.keys(S.codeRed.results||{}).length),first=(S.profile.displayName||'나').slice(0,1);
 $('#view').innerHTML=`<section class="world-hero"><div class="hero-profile"><div class="user-chip">${av?`<img class="avatar-circle" src="${av}" alt="사용자 프로필">`:`<div class="avatar-circle avatar-fallback">${esc(first)}</div>`}<div><b>${esc(S.profile.displayName||'탐험가')}</b><small>Lv.${Math.floor(S.xp/100)+1} · ${S.xp} XP</small></div></div><img class="guide-peek" src="${guideAsset('smile')}" alt="${esc(S.guide.name||'길잡이')}"></div><div class="hero-case"><div class="hero-kicker"><span>ACTIVE WORD TRAIL</span><span>${stateLabel(sh.status)}</span></div><h1>${esc(sh.title)}</h1><p>${ws.length}단어 · 취약 ${weak}개 · FINAL SEEK 남은 ${remain}개</p><div class="progress" style="margin-top:8px"><span style="width:${progress}%"></span></div><div class="hero-actions"><button class="btn primary" id="photoFirst" type="button">사진으로 시험지 만들기</button><button class="btn secondary" id="continueCase" type="button">이어하기</button></div></div></section>
 <section class="primary-intake"><div><h2>새 시험지 접수</h2><p>촬영/사진 추가 → 즉시 임시저장 → 여기까지 분석 → OCR SEE/PAIR → 확인 → 저장 순서로 진행합니다.</p><div class="btn-row" style="margin-top:10px"><button class="btn dark" id="homeCamera" type="button">카메라</button><button class="btn secondary" id="homeLibrary" type="button">사진 보관함</button></div></div><img class="intake-illustration" src="${guideAsset('note')}" alt=""></section>
 <div class="section-title"><h2>오늘의 학습 상태</h2><span>Trail Mastery ≠ Memory Strength</span></div><section class="status-strip"><div class="status-pill"><b>${sh.caseMastery||0}%</b><span>Trail Mastery</span></div><div class="status-pill"><b>${memoryStrength()}%</b><span>Memory</span></div><div class="status-pill"><b>${S.streak}일</b><span>연속 학습</span></div></section>
 <div class="section-title"><h2>나의 길잡이</h2><span>기능 차등 없음</span></div><section class="card tint-sky"><div class="partner-mini"><img src="${guideAsset('default')}" alt=""><div><b>${esc(S.guide.name||'길잡이')}</b><p>${GUIDE_OPTIONS.find(x=>x.id===S.guide.id)?.label||'나의 길잡이'} · ${GUIDE_OPTIONS.find(x=>x.id===S.guide.id)?.tone||''}</p></div></div></section>`;
 $('#photoFirst').onclick=()=>{$('#sheetCameraInput').click()};$('#homeCamera').onclick=()=>$('#sheetCameraInput').click();$('#homeLibrary').onclick=()=>$('#sheetLibraryInput').click();$('#continueCase').onclick=()=>{currentTab='study';render()};setPartner('새 시험지가 최우선이야. 준비됐으면 바로 촬영하자.','default')
}
function renderSheets(){
 $('#view').innerHTML=`<div class="section-title"><h2>시험지</h2><span>Camera First</span></div><section class="primary-intake"><div><h2>새 시험지 만들기</h2><p>사진은 즉시 임시저장되고, OCR 결과는 시험지 저장 전에 확인합니다.</p><div class="btn-row" style="margin-top:10px"><button class="btn primary" id="cameraSheet" type="button">카메라로 찍기</button><button class="btn secondary" id="librarySheet" type="button">사진 보관함</button></div></div><img class="intake-illustration" src="${guideAsset('focus')}" alt=""></section><div class="section-title"><h2>시험지</h2><span>${S.sheets.length}개</span></div>${S.sheets.map(sh=>`<section class="card" style="margin-bottom:8px"><div class="hero-kicker"><span>${stateLabel(sh.status)}</span><span>${(sh.items||[]).filter(w=>!w.needsReview).length}단어</span></div><h3>${esc(sh.title)}</h3><div class="progress" style="margin:10px 0"><span style="width:${sh.caseMastery||0}%"></span></div><div class="btn-row"><button class="btn secondary open-sheet" data-id="${esc(sh.sheetId)}" type="button">열기</button><button class="btn secondary review-sheet" data-id="${esc(sh.sheetId)}" type="button">단어 확인</button></div></section>`).join('')}`;
 if(S.captureSession?.status==="OPEN"&&S.captureSession.pages?.length){const resume=document.createElement("section");resume.className="card tint-sky";resume.style.marginBottom="9px";resume.innerHTML=`<div class="hero-kicker"><span>CAPTURE SESSION</span><span>${S.captureSession.pages.length}장</span></div><h3>진행 중인 촬영</h3><p>화면을 이동해도 임시저장된 사진은 유지됩니다.</p><button class="btn primary full" id="resumeCapture" style="margin-top:10px" type="button">촬영 이어가기</button>`;$("#view").prepend(resume);$("#resumeCapture").onclick=()=>pushView(renderCaptureSession)}
$('#cameraSheet').onclick=()=>$('#sheetCameraInput').click();$('#librarySheet').onclick=()=>$('#sheetLibraryInput').click();$$('.open-sheet').forEach(b=>b.onclick=()=>{S.activeSheetId=b.dataset.id;save();currentTab='study';render()});$$('.review-sheet').forEach(b=>b.onclick=()=>{S.activeSheetId=b.dataset.id;save();renderOCRReview(allWords(),false)});setPartner('필요한 시험지를 여기서 골라볼까?','note')
}
async function preflightImage(file){
 if(!file||file.size<=0)throw new Error('빈 파일이에요.');if(!/^image\//.test(file.type||''))throw new Error('이미지 파일을 선택해 주세요.');if(file.size>20*1024*1024)throw new Error('사진이 너무 커요. 20MB 이하 사진을 사용해 주세요.');
 let bmp;try{bmp=await createImageBitmap(file,{imageOrientation:'from-image'})}catch{throw new Error('사진을 열 수 없어요. 다른 사진으로 다시 시도해 주세요.')}
 const short=Math.min(bmp.width,bmp.height),long=Math.max(bmp.width,bmp.height),warnings=[];if(short<700)warnings.push('해상도가 낮아요');if(long<1200)warnings.push('글자가 작게 보일 수 있어요');const ratio=long/Math.max(1,short);if(ratio>4.5)warnings.push('사진 비율이 너무 길어요');return {width:bmp.width,height:bmp.height,warnings,quality:warnings.length?'확인 필요':'양호'}
}
function ensureCaptureSession(){
 if(!S.captureSession||S.captureSession.status!=="OPEN")S.captureSession={sessionId:`capture-${Date.now()}`,status:"OPEN",createdAt:nowISO(),updatedAt:nowISO(),pages:[],analysisBatches:[],lastCommittedAt:""};
 S.captureSession.pages=Array.isArray(S.captureSession.pages)?S.captureSession.pages:[];
 S.captureSession.analysisBatches=Array.isArray(S.captureSession.analysisBatches)?S.captureSession.analysisBatches:[];
 return S.captureSession;
}
function capturePageKey(sessionId,pageId){return `capture:${sessionId}:${pageId}`}
async function captureFiles(files,sourceType="camera"){
 const list=[...(files||[])].filter(Boolean);if(!list.length)return;
 const session=ensureCaptureSession();let saved=0,failed=0;
 for(const file of list){
  try{
   const q=await preflightImage(file),pageId=`page-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,assetKey=capturePageKey(session.sessionId,pageId);
   await dbSet(assetKey,file);
   session.pages.push({pageId,assetKey,sourceType,fileName:file.name||"",mime:file.type||"image/jpeg",size:file.size,width:q.width,height:q.height,quality:q.quality,warnings:q.warnings,capturedAt:nowISO(),analyzedAt:""});
   saved++;
  }catch(e){failed++;toast(e.message||"사진을 저장하지 못했어요.")}
 }
 session.updatedAt=nowISO();save();
 const cam=$("#sheetCameraInput"),lib=$("#sheetLibraryInput");if(cam)cam.value="";if(lib)lib.value="";
 if(saved){viewStack=[];pushView(()=>renderCaptureSession(failed?`${saved}장 저장 · ${failed}장 제외`:"촬영 즉시 저장 완료"));setPartner("좋아, 다음 장도 이어서 가자.","note")}
}
function renderCaptureSession(notice=""){
 const session=ensureCaptureSession(),pages=session.pages||[],pending=pages.filter(p=>!p.analyzedAt);
 $("#view").innerHTML=`<section class="capture-shell"><div class="hero-kicker"><span>CAPTURE SESSION</span><span>${session.status}</span></div><h2>시험지 연속 촬영</h2><p>${notice||"촬영하면 확인 화면 없이 바로 임시 저장됩니다. 필요한 만큼 찍은 뒤 ‘여기까지 분석’을 누르세요."}</p><div class="capture-summary"><b>${pages.length}장 저장</b><span>${pending.length}장 분석 대기</span></div><div class="capture-list">${pages.map((p,i)=>`<div class="capture-page"><div><b>${i+1}번째 사진</b><small>${p.width}×${p.height} · ${Math.round((p.size||0)/1024)}KB</small></div><span class="badge ${p.analyzedAt?"good":p.warnings?.length?"weak":"mid"}">${p.analyzedAt?"분석됨":p.warnings?.length?"확인 필요":"저장됨"}</span></div>`).join("")||"<p>아직 저장된 사진이 없어요.</p>"}</div><div class="btn-row" style="margin-top:13px"><button class="btn primary" id="captureMore" type="button">계속 촬영</button><button class="btn secondary" id="captureLibrary" type="button">사진 추가</button></div><button class="btn dark full" id="analyzeBatch" style="margin-top:8px" type="button" ${pending.length?"":"disabled"}>여기까지 분석</button><button class="btn secondary full" id="finishCapture" style="margin-top:8px" type="button">촬영 끝내기</button>${S.activeSheetId&&sheet()?'<button class="btn secondary full" id="goActiveSheet" style="margin-top:8px" type="button">현재 시험지 학습으로</button>':""}</section>`;
 $("#captureMore").onclick=()=>$("#sheetCameraInput").click();$("#captureLibrary").onclick=()=>$("#sheetLibraryInput").click();$("#analyzeBatch").onclick=analyzeCaptureBatch;
 $("#finishCapture").onclick=()=>{session.status="CLOSED";session.closedAt=nowISO();session.updatedAt=nowISO();save();currentTab="sheets";viewStack=[];render();toast("촬영 세션을 종료했어요.")};
 $("#goActiveSheet")?.addEventListener("click",()=>{currentTab="study";viewStack=[];render()});
}
async function analyzeCaptureBatch(){
 const session=ensureCaptureSession(),targets=(session.pages||[]).filter(p=>!p.analyzedAt);
 if(!targets.length)return toast("새로 분석할 사진이 없어요.");
 if(!navigator.onLine)return toast("OCR 분석은 온라인 연결이 필요해요. 저장된 사진은 그대로 유지됩니다.");
 if(!runtimeApiKey)return pushView(()=>renderManualEntry("API Key가 없어 OCR을 실행하지 않았어요. 저장된 촬영 세션은 유지됩니다."));
 $("#view").innerHTML=`<section class="card"><div class="hero-kicker"><span>OCR BATCH</span><span>${targets.length} page</span></div><h2>여기까지 분석 중</h2><p id="ocrStage">SEE · 각 사진에서 실제 보이는 문자열만 확인 중</p><div class="progress" style="margin-top:16px"><span id="ocrProgress" style="width:8%"></span></div></section>`;
 try{
  const seen=[];
  for(let i=0;i<targets.length;i++){
   const p=targets[i],file=await dbGet(p.assetKey);if(!file)throw new Error(`${i+1}번째 저장 사진을 찾을 수 없어요.`);
   const img=await normalizedImageBase64(file),seePrompt=`사진에 실제로 보이는 영어 단어와 한글 뜻만 행 순서대로 전사하세요. 원본에 없는 단어를 만들지 말고, 예문/힌트/정답 추측을 하지 마세요. 불확실하면 confidence를 low로 표시하세요. JSON만 출력: {"rows":[{"eng":"...","kor":"...","confidence":"high|medium|low"}]}`,see=await gemini(seePrompt,img.b64,img.mime);
   (see.rows||[]).forEach(r=>seen.push({...r,sourcePageId:p.pageId}));$("#ocrProgress").style.width=`${Math.round(8+52*(i+1)/targets.length)}%`;
  }
  $("#ocrStage").textContent="PAIR · 전체 촬영분에서 단어와 뜻의 대응 확인 중";
  const pairPrompt=`아래 SEE OCR 행만 사용해 영어 단어-한국어 뜻의 짝을 검증하세요. 원본에 없는 새 단어를 만들지 마세요. 헤더/번호/잡음은 제외하고 원래 순서를 유지하세요. 애매한 행은 low로 남기세요. sourcePageId를 유지하세요. JSON만 출력: {"rows":[{"eng":"...","kor":"...","confidence":"high|medium|low","sourcePageId":"..."}]}\nSEE:\n${JSON.stringify({rows:seen})}`;
  const paired=await gemini(pairPrompt),rows=(paired.rows||seen).filter(x=>x.eng||x.kor).map((x,i)=>normalizeWord({id:`ocr-${Date.now()}-${i}`,eng:x.eng,kor:x.kor,confidence:x.confidence||"medium",needsReview:x.confidence==="low",sourcePageId:x.sourcePageId},i));
  if(!rows.length)throw new Error("단어와 뜻을 찾지 못했어요.");
  const batchId=`batch-${Date.now()}`;targets.forEach(p=>p.analyzedAt=nowISO());session.analysisBatches.push({batchId,pageIds:targets.map(p=>p.pageId),createdAt:nowISO(),rowCount:rows.length});session.updatedAt=nowISO();
  S.ocrDraft={createdAt:nowISO(),captureSessionId:session.sessionId,batchId,pageIds:targets.map(p=>p.pageId),rows};save();$("#ocrProgress").style.width="100%";renderOCRReview(rows,true);
 }catch(e){toast(`OCR 실패: ${e.message||"다시 시도해 주세요."}`);renderCaptureSession("분석에 실패했지만 촬영 원본과 세션은 그대로 보존됐어요.")}
}
async function normalizedImageBase64(file,maxLong=2400){const bmp=await createImageBitmap(file,{imageOrientation:'from-image'}),scale=Math.min(1,maxLong/Math.max(bmp.width,bmp.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(bmp.width*scale));c.height=Math.max(1,Math.round(bmp.height*scale));const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(bmp,0,0,c.width,c.height);const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.9));return new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res({b64:String(fr.result).split(',')[1],mime:'image/jpeg'});fr.onerror=()=>rej(fr.error);fr.readAsDataURL(blob)})}
async function gemini(prompt,b64,mime){const parts=[{text:prompt}];if(b64)parts.push({inlineData:{mimeType:mime,data:b64}});const model=encodeURIComponent(S.settings.geminiModel||'gemini-2.5-flash'),r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':runtimeApiKey},body:JSON.stringify({contents:[{parts}],generationConfig:{responseMimeType:'application/json'}})});if(!r.ok){if(r.status===401||r.status===403)throw new Error('API 인증을 확인해 주세요.');if(r.status===429)throw new Error('요청이 많아요. 잠시 후 다시 시도해 주세요.');throw new Error(`네트워크/API 오류 ${r.status}`)}const j=await r.json(),txt=j.candidates?.[0]?.content?.parts?.[0]?.text||'{}';return JSON.parse(txt)}
function renderManualEntry(message='단어와 뜻을 직접 입력할 수 있어요.'){renderOCRReview([{id:`manual-${Date.now()}`,eng:'',kor:'',confidence:'manual',needsReview:true}],true,message)}
function renderOCRReview(rows,isDraft=false,message=""){
 let data=rows.map(normalizeWord);
 $("#view").innerHTML=`<section class="card"><div class="hero-kicker"><span>REVIEW BEFORE COMMIT</span><span>${data.length}개</span></div><h2>OCR 결과 확인</h2><p>${message||`${data.length}개를 찾았어요. ‘확인 필요’ 행은 직접 확인 완료해야 학습에 포함됩니다.`}</p><div class="table" id="ocrRows" style="margin-top:12px"></div><div class="btn-row" style="margin-top:13px"><button class="btn secondary" id="addOcrRow" type="button">행 추가</button><button class="btn primary" id="commitSheet" type="button">시험지 만들기</button></div></section>`;
 const draw=()=>{
  $("#ocrRows").innerHTML=data.map((w,i)=>`<div class="row review-row" data-i="${i}"><input class="eng" value="${esc(w.eng)}" aria-label="${i+1}번 영어 단어"><input class="kor" value="${esc(w.kor)}" aria-label="${i+1}번 뜻"><span class="badge ${w.needsReview?"weak":"good"}">${w.needsReview?"확인 필요":"확인"}</span>${w.needsReview?`<button class="review-confirm" data-confirm="${i}" type="button">확인 완료</button>`:""}<button class="row-delete" data-del="${i}" type="button" aria-label="${i+1}번 행 삭제">×</button></div>`).join("");
  $$("[data-del]").forEach(b=>b.onclick=()=>{data.splice(Number(b.dataset.del),1);draw()});
  $$("[data-confirm]").forEach(b=>b.onclick=()=>{const i=Number(b.dataset.confirm);data[i].needsReview=false;data[i].reviewConfirmed=true;draw()});
 };
 draw();
 $("#addOcrRow").onclick=()=>{data.push(normalizeWord({id:`manual-${Date.now()}`,eng:"",kor:"",confidence:"manual",needsReview:true},data.length));draw()};
 $("#commitSheet").onclick=()=>{
  const out=$$("#ocrRows .row").map((r,i)=>{const eng=$(".eng",r).value.trim(),kor=$(".kor",r).value.trim(),edited=eng!==String(data[i].eng||"").trim()||kor!==String(data[i].kor||"").trim();return normalizeWord({...data[i],eng,kor,needsReview:!!data[i].needsReview,manuallyEdited:!!data[i].manuallyEdited||edited,reviewConfirmed:!!data[i].reviewConfirmed},i)}).filter(x=>x.eng&&x.kor);
  if(!out.length)return toast("단어와 뜻을 한 개 이상 입력해 주세요.");
  const unresolved=out.filter(x=>x.needsReview).length,newId=isDraft?`sheet-${Date.now()}`:sheet().sheetId,capturePages=S.ocrDraft?.pageIds?.length||1,newSheet={sheetId:newId,title:isDraft?`${new Date().toLocaleDateString("ko-KR")} 시험지`:sheet().title,createdAt:isDraft?nowISO():sheet().createdAt,updatedAt:nowISO(),testDate:"",sourceType:isDraft?(S.ocrDraft?.captureSessionId?"capture-session":"photo"):"existing",sourceCount:isDraft?capturePages:(sheet().sourceCount||0),status:unresolved?"REVIEW_REQUIRED":"READY",caseMastery:0,items:out,recognitionMeta:{reviewedAt:nowISO(),count:out.length,unresolved,captureSessionId:S.ocrDraft?.captureSessionId||"",batchId:S.ocrDraft?.batchId||""}};
  if(isDraft){S.sheets.unshift(newSheet);S.activeSheetId=newId}else Object.assign(sheet(),newSheet);
  if(S.captureSession&&S.ocrDraft?.captureSessionId===S.captureSession.sessionId){S.captureSession.lastCommittedAt=nowISO();S.captureSession.updatedAt=nowISO()}
  S.ocrDraft=null;S.learning=clone(DEFAULT_STATE.learning);S.codeRed=clone(DEFAULT_STATE.codeRed);save();
  toast(unresolved?`저장 완료 · 확인 필요 ${unresolved}개는 학습에서 제외돼요.`:"시험지 저장 완료");
  if(S.captureSession?.status==="OPEN"){viewStack=[];renderCaptureSession("분석 결과를 저장했어요. 촬영 세션은 계속 열려 있습니다.")}else{currentTab="study";viewStack=[];render()}
 };
 setPartner("확실한 건 두고, 애매한 행만 같이 확인해보자.","note")
}
function resumeCurrentLearning(){const st=sheet()?.status||"READY";if(st==="CODE_RED_READY"){viewStack=[];return renderCodeRed()}if(st==="RETRACE_REQUIRED"){viewStack=[];return renderRetrace()}if(st==="TEST_READY"||st==="COMPLETED"){viewStack=[];return renderComplete()}const phase=S.learning.phase||"first";const map={first:renderFirstContact,meaning:renderMeaningCheck,connection:renderConnection,weak:renderWeak,code:renderCodeRed,done:renderComplete};viewStack=[];(map[phase]||renderFirstContact)()}
function renderLearningHub(){const ws=validWords();if(!ws.length)return renderSheets();const sh=sheet(),weak=ws.filter(w=>weakScore(w)>0).length,resumable=["LEARNING","CODE_RED_READY","RETRACE_REQUIRED"].includes(sh.status);$('#view').innerHTML=`<section class="learning-shell"><div class="learn-head"><div><span class="phase-chip">${stateLabel(sh.status)}</span><h2 style="margin:5px 0 0">${esc(sh.title)}</h2></div><div style="text-align:right"><b>${ws.length}단어</b><small style="display:block">취약 ${weak}개</small></div></div><div class="progress" style="margin-top:10px"><span style="width:${learningProgress()}%"></span></div>${resumable?'<button class="btn primary full" id="resumeLearning" style="margin-top:10px" type="button">이어서 학습</button>':''}<div class="section-title"><h2>학습 미션</h2><span>보고 → 뜻 → 연결 → 취약 → 검증</span></div><div class="grid2"><button class="mission-card" id="phaseFirst" type="button"><h3>FIRST FIND</h3><p>보고, 듣고, 뜻과 철자 형태를 익혀요.</p></button><button class="mission-card" id="phaseMeaning" type="button"><h3>MEANING CLUE</h3><p>영어↔뜻을 양방향 4지선다로 확인해요.</p></button><button class="mission-card" id="phaseConnect" type="button"><h3>CONNECTION TRAIL</h3><p>단어와 뜻을 빠르게 타일로 연결해요.</p></button><button class="mission-card" id="phaseWeak" type="button"><h3>HIDDEN WORDS</h3><p>오답·PASS·힌트 단어를 더 자주 만나요.</p></button></div><button class="btn danger full" id="phaseCode" style="margin-top:9px" type="button">FINAL SEEK · 전체 철자 최종 검증</button></section>`;$('#resumeLearning')?.addEventListener('click',resumeCurrentLearning);$('#phaseFirst').onclick=()=>pushView(renderFirstContact);$('#phaseMeaning').onclick=()=>pushView(renderMeaningCheck);$('#phaseConnect').onclick=()=>pushView(renderConnection);$('#phaseWeak').onclick=()=>pushView(renderWeak);$('#phaseCode').onclick=()=>startCodeRed(false);setPartner('먼저 충분히 익히고, 약한 단어를 더 보고, 마지막에 전체 철자를 확인하자.','default')}
function renderFirstContact(){const ws=validWords(),i=S.learning.firstIndex%ws.length,w=ws[i];sheet().status='LEARNING';S.learning.phase='first';save();$('#view').innerHTML=`<section class="learning-shell"><div class="learn-head"><div><span class="phase-chip">FIRST FIND</span><h2 style="margin:5px 0 0">신규 단어 습득</h2></div><b>${i+1}/${ws.length}</b></div><div class="progress" style="margin-top:9px"><span style="width:${Math.round((i+1)/ws.length*100)}%"></span></div><section class="card word-card"><div class="eng">${esc(w.eng)}</div><button class="circle-btn" id="speakWord" type="button" style="margin:10px auto 0">발음</button><div class="kor">${esc(w.kor)}</div>${w.example?`<div class="example">${esc(w.example)}</div>`:''}<div class="btn-row" style="margin-top:17px"><button class="btn secondary" id="firstUnsure" type="button">아직 헷갈려</button><button class="btn primary" id="firstNext" type="button">다음 단어</button></div></section></section>`;$('#speakWord').onclick=()=>speakWord(w.eng);$('#firstUnsure').onclick=()=>{w.wrong=(w.wrong||0)+1;advanceFirst(false)};$('#firstNext').onclick=()=>advanceFirst(true);setPartner('지금은 시험이 아니야. 소리와 뜻, 철자 모양을 편하게 연결해둬.','default')}
function advanceFirst(ok){const ws=validWords();markStudy(ok?2:1);S.learning.firstIndex++;if(S.learning.firstIndex>=ws.length){S.learning.firstIndex=0;S.learning.phase='meaning';save();renderMeaningCheck()}else{save();renderFirstContact()}}
function optionLabel(w,field){return String(field==='kor'?w.kor:w.eng).trim().replace(/\s+/g,' ')}
function choiceOptions(correct,field){const correctLabel=optionLabel(correct,field).toLowerCase(),seen=new Set([correctLabel]),pool=shuffle(validWords().filter(x=>x.id!==correct.id)).filter(x=>{const label=optionLabel(x,field).toLowerCase();if(!label||seen.has(label))return false;seen.add(label);return true});return shuffle([correct,...pool.slice(0,3)]).map(x=>({id:x.id,label:optionLabel(x,field)}))}
function renderMeaningCheck(){const ws=validWords(),i=S.learning.meaningIndex%ws.length,w=ws[i],reverse=i%2===1,field=reverse?'eng':'kor',prompt=reverse?w.kor:w.eng,opts=choiceOptions(w,field);S.learning.phase='meaning';S.learning.meaningStartedAt=Date.now();sheet().status='LEARNING';save();$('#view').innerHTML=`<section class="learning-shell"><div class="learn-head"><div><span class="phase-chip">MEANING CLUE</span><h2 style="margin:5px 0 0">${reverse?'뜻 → 영어':'영어 → 뜻'}</h2></div><b>${i+1}/${ws.length}</b></div><section class="card word-card"><div class="eng" style="font-size:${reverse?'23px':'31px'}">${esc(prompt)}</div><div class="choice-grid">${opts.map(o=>`<button class="choice" data-choice="${esc(o.id)}" type="button">${esc(o.label)}</button>`).join('')}</div></section></section>`;$$('[data-choice]').forEach(b=>b.onclick=()=>meaningAnswer(b,w,b.dataset.choice===w.id));setPartner('정답을 외워 찍기보다, 영어와 뜻의 연결을 빠르게 확인해보자.','focus')}
function meaningAnswer(btn,w,ok){$$('[data-choice]').forEach(b=>b.disabled=true);btn.classList.add(ok?'correct':'wrong');const elapsedMs=Math.max(0,Date.now()-Number(S.learning.meaningStartedAt||Date.now())),slow=ok&&elapsedMs>=7000;if(!ok){w.wrong=(w.wrong||0)+1;setPartner('이 단어는 추적 목록에 넣어둘게. 뒤에서 더 자주 만나자.','note')}else{w.learningStats=w.learningStats||{};if(slow)w.learningStats.slowCorrect=(w.learningStats.slowCorrect||0)+1;S.learning.combo++;S.learning.flow=Math.min(6,S.learning.flow+1)}S.learning.history.push({at:nowISO(),mode:'meaning',wordId:w.id,result:ok?(slow?'SLOW_CORRECT':'CORRECT'):'WRONG',elapsedMs});markStudy(ok?3:1);setTimeout(()=>{S.learning.meaningIndex++;if(S.learning.meaningIndex>=validWords().length){S.learning.meaningIndex=0;S.learning.phase='connection';save();renderConnection()}else{save();if(ok&&S.learning.combo>0&&S.learning.combo%5===0)triggerFever(()=>renderMeaningCheck());else renderMeaningCheck()}},350)}
function connectionSet(){const words=validWords(),baseRounds=Math.ceil(words.length/4),round=S.learning.connectionRound;if(round<baseRounds)return words.slice(round*4,Math.min(words.length,round*4+4));return [...words].filter(w=>weakScore(w)>0).sort((a,b)=>weakScore(b)-weakScore(a)).slice(0,Math.min(4,words.length))}
function renderConnection(){const set=connectionSet();selectedTile=null;S.learning.phase='connection';save();const left=shuffle(set),right=shuffle(set);$('#view').innerHTML=`<section class="learning-shell"><div class="learn-head"><div><span class="phase-chip">CONNECTION TRAIL</span><h2 style="margin:5px 0 0">단어와 뜻 연결</h2></div><b>Round ${S.learning.connectionRound+1}</b></div><section class="card"><p>왼쪽 영어 하나와 오른쪽 뜻 하나를 차례로 선택하세요.</p><div class="tile-board"><div>${left.map(w=>`<button class="tile tile-eng" data-id="${w.id}" data-side="eng" type="button">${esc(w.eng)}</button>`).join('')}</div><div>${right.map(w=>`<button class="tile tile-kor" data-id="${w.id}" data-side="kor" type="button">${esc(w.kor)}</button>`).join('')}</div></div><button class="btn primary full" id="connectionNext" style="margin-top:12px" type="button" disabled>다음 라운드</button></section></section>`;$$('.tile').forEach(b=>b.onclick=()=>tilePick(b));setPartner('이번엔 단어와 뜻을 빠르게 연결해보자. 틀려도 바로 다음 단서로 가면 돼.','play')}
function tilePick(btn){if(btn.classList.contains('matched'))return;if(!selectedTile){selectedTile=btn;btn.classList.add('selected');return}if(selectedTile.dataset.side===btn.dataset.side){selectedTile.classList.remove('selected');selectedTile=btn;btn.classList.add('selected');return}const ok=selectedTile.dataset.id===btn.dataset.id,id=btn.dataset.id;if(ok){$$(`.tile[data-id="${id}"]`).forEach(x=>x.classList.add('matched'));S.learning.combo++;S.learning.flow=Math.min(6,S.learning.flow+1);markStudy(2)}else{const w=validWords().find(x=>x.id===selectedTile.dataset.id);if(w)w.wrong=(w.wrong||0)+1;markStudy(1);setPartner('연결이 살짝 엇갈렸네. 두 단서를 다시 보고 이어가자.','think')}selectedTile.classList.remove('selected');selectedTile=null;if($$('.tile:not(.matched)').length===0){$('#connectionNext').disabled=false;$('#connectionNext').onclick=()=>{const words=validWords(),baseRounds=Math.ceil(words.length/4),hasWeak=words.some(w=>weakScore(w)>0),lastRound=baseRounds+(hasWeak?1:0)-1;S.learning.connectionRound++;if(S.learning.connectionRound>lastRound){S.learning.connectionRound=0;S.learning.phase='weak';save();renderWeak()}else{save();renderConnection()}}}}
function renderWeak(){const ordered=[...validWords()].sort((a,b)=>weakScore(b)-weakScore(a)),weak=ordered.filter(w=>weakScore(w)>0),top=(weak.length?weak:ordered).slice(0,Math.min(6,ordered.length));S.learning.phase='weak';save();$('#view').innerHTML=`<section class="learning-shell"><div class="learn-head"><div><span class="phase-chip">HIDDEN WORDS</span><h2 style="margin:5px 0 0">어려운 단어 집중</h2></div><b>${top.length}개</b></div><section class="card"><div class="flow-gauge">${[0,1,2,3,4,5].map(i=>`<i class="${i<S.learning.flow?'on':''}"></i>`).join('')}</div><div class="weak-list" style="margin-top:13px">${top.map(w=>`<div class="weak-item"><div><b>${esc(w.eng)}</b><div style="font-size:10px;color:#66736a">${esc(w.kor)}</div></div><span class="badge ${weakScore(w)>=8?'weak':'mid'}">${weakScore(w)>=8?'집중':'확인'}</span></div>`).join('')}</div><div class="btn-row" style="margin-top:13px"><button class="btn secondary" id="weakReplay" type="button">취약 단어 다시 보기</button><button class="btn danger" id="weakToCode" type="button">FINAL SEEK</button></div></section></section>`;$('#weakReplay').onclick=()=>{const first=top[0];S.learning.firstIndex=Math.max(0,validWords().findIndex(w=>w.id===first.id));save();renderFirstContact()};$('#weakToCode').onclick=()=>startCodeRed(false);setPartner('약한 단어에 시간을 더 쓰되, 전체 단어를 마지막 FINAL SEEK에서 전부 확인할게.','focus')}
function triggerFever(next){S.learning.fever=true;save();$('#view').innerHTML=`<section class="card fever-stage"><div class="food-rain"><i class="food" style="left:8%">PIZZA</i><i class="food">DONUT</i><i class="food">JUICE</i><i class="food">BURGER</i><i class="food">FRUIT</i></div><div style="position:relative;z-index:2;text-align:center;padding-top:54px"><h1 style="font-size:35px;margin:0;color:#4d783e">FEVER TIME</h1><p>연속 성공 보너스 · 학습 판정은 그대로</p><div class="flow-gauge" style="max-width:290px;margin:17px auto">${[0,1,2,3,4,5].map(()=>'<i class="on"></i>').join('')}</div><button class="btn primary" id="leaveFever" type="button">계속 학습</button></div></section>`;setPartner('흐름 좋네. 잠깐 축제다. 문제는 그대로 차분하게 가자.','fever',true);$('#leaveFever').onclick=()=>{S.learning.fever=false;S.learning.flow=0;save();next()}}
function blankCount(word){const n=word.length;return n<=5?Math.min(2,Math.max(1,n-2)):n<=8?3:Math.min(4,n-2)}
function makeCodeSession(w){const n=blankCount(w.eng),idx=shuffle([...w.eng].map((_,i)=>i)).slice(0,n).sort((a,b)=>a-b),real=idx.map((i,k)=>({id:`r${k}-${Math.random()}`,ch:w.eng[i].toLowerCase(),real:true})),required=new Set(real.map(x=>x.ch)),alphabet='abcdefghijklmnopqrstuvwxyz',fakes=[];while(fakes.length<Math.max(3,n)){const ch=alphabet[Math.floor(Math.random()*alphabet.length)];if(!required.has(ch))fakes.push({id:`f${fakes.length}-${Math.random()}`,ch,real:false})}return {word:w,blankIdx:idx,keys:shuffle([...real,...fakes]),answers:{},hintLevel:0,wrongAttempts:0,seconds:S.settings.pressureReduced?24:(w.eng.length<=5?15:w.eng.length<=8?18:21),start:Date.now()}}
function codeTargets(){const ws=validWords();if(S.codeRed.retryOnly){const set=new Set(S.codeRed.targetIds.length?S.codeRed.targetIds:S.codeRed.retrace);return ws.filter(w=>set.has(w.id))}return ws}
function startCodeRed(retryOnly=false){stopCodeTimer();const targets=retryOnly?validWords().filter(w=>S.codeRed.retrace.includes(w.id)):validWords();if(!targets.length)return toast('FINAL SEEK 대상 단어가 없어요.');const sh=sheet();sh.learningProvenance=sh.learningProvenance||{};sh.learningProvenance.startedAt=sh.learningProvenance.startedAt||nowISO();sh.learningProvenance.lastActivityAt=nowISO();sh.learningProvenance.seekAgainCycles=Number(sh.learningProvenance.seekAgainCycles||0)+(retryOnly?1:0);S.learning.phase='code';sh.status='CODE_RED_READY';S.codeRed.index=0;S.codeRed.retryOnly=retryOnly;S.codeRed.targetIds=targets.map(w=>w.id);if(!retryOnly){S.codeRed.results={};S.codeRed.retrace=[]}save();viewStack=[];renderCodeRed()}
function renderCodeRed(){const targets=codeTargets();if(S.codeRed.index>=targets.length)return finishCodeRed();const w=targets[S.codeRed.index];codeSession=makeCodeSession(w);selectedKey=null;const letters=[...w.eng].map((ch,i)=>codeSession.blankIdx.includes(i)?`<span class="slot-anchor">_</span>`:esc(ch)).join('');$('#view').innerHTML=`<section class="code-shell"><div class="code-head"><div><span class="code-label">FINAL SEEK</span><div class="code-instruction" style="margin-top:6px">${S.codeRed.retryOnly?'RE-CHECK':'ALL CURRENT WORDS'} · ${S.codeRed.index+1}/${targets.length}</div></div><div id="timeRing" class="time-ring" style="--p:100"><b><span id="timeText">${codeSession.seconds}</span>s</b></div></div><div class="code-word"><div>${letters}</div><div class="slots">${codeSession.blankIdx.map((_,n)=>`<button class="slot" data-slot="${n}" type="button" aria-label="${n+1}번째 빈칸"></button>`).join('')}</div></div><p class="code-instruction">Letter Key를 빈칸으로 끌거나, Key를 탭한 뒤 Slot을 탭하세요.</p><div class="key-tray">${codeSession.keys.map(k=>`<button draggable="true" class="letter-key" data-key="${k.id}" type="button">${esc(k.ch)}</button>`).join('')}</div><div class="btn-row"><button class="btn gold" id="codeHint" type="button">힌트</button><button class="btn secondary" id="undoCode" type="button">되돌리기</button><button class="btn danger" id="passCode" type="button">PASS</button></div></section>`;bindCodeRed();startCodeTimer();setPartner('진짜 철자 열쇠만 골라. 가짜도 섞여 있어.','radio')}
function bindCodeRed(){$$('.letter-key').forEach(k=>{k.onclick=()=>selectKey(k.dataset.key);k.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',k.dataset.key))});$$('.slot').forEach(s=>{s.onclick=()=>placeSelected(Number(s.dataset.slot));s.addEventListener('dragover',e=>e.preventDefault());s.addEventListener('drop',e=>{e.preventDefault();placeKey(e.dataTransfer.getData('text/plain'),Number(s.dataset.slot))})});$('#undoCode').onclick=undoCode;$('#codeHint').onclick=useCodeHint;$('#passCode').onclick=()=>recordCodeResult('PASS')}
function selectKey(id){selectedKey=id;$$('.letter-key').forEach(k=>k.classList.toggle('selected',k.dataset.key===id))}
function placeSelected(slot){if(selectedKey)placeKey(selectedKey,slot)}
function placeKey(keyId,slot){const key=codeSession.keys.find(k=>k.id===keyId);if(!key||key.used)return;const need=codeSession.word.eng[codeSession.blankIdx[slot]].toLowerCase();if(key.ch!==need){codeSession.wrongAttempts++;selectedKey=null;$$('.letter-key').forEach(k=>k.classList.remove('selected'));const el=$(`[data-key="${CSS.escape(keyId)}"]`);if(el){el.classList.remove('reject');void el.offsetWidth;el.classList.add('reject')}setPartner('가짜 열쇠였네. 원래 자리로 돌려둘게.','focus');return}const prev=codeSession.answers[slot];if(prev){const pk=codeSession.keys.find(k=>k.id===prev);if(pk)pk.used=false}codeSession.answers[slot]=key.id;key.used=true;selectedKey=null;updateCodeUI();if(Object.keys(codeSession.answers).length===codeSession.blankIdx.length)setTimeout(checkCodeAnswer,180)}
function updateCodeUI(){$$('.slot').forEach(s=>{const id=codeSession.answers[Number(s.dataset.slot)],key=codeSession.keys.find(k=>k.id===id);s.textContent=key?.ch||'';s.classList.toggle('filled',!!key)});$$('.letter-key').forEach(el=>{const key=codeSession.keys.find(x=>x.id===el.dataset.key);el.classList.toggle('used',!!key?.used);el.classList.remove('selected')})}
function undoCode(){const slots=Object.keys(codeSession.answers);if(!slots.length)return;const last=slots.at(-1),id=codeSession.answers[last],k=codeSession.keys.find(x=>x.id===id);if(k)k.used=false;delete codeSession.answers[last];updateCodeUI()}
function useCodeHint(){codeSession.hintLevel++;const unanswered=codeSession.blankIdx.map((_,i)=>i).filter(i=>!codeSession.answers[i]);if(!unanswered.length)return;const slot=unanswered[0],needed=codeSession.word.eng[codeSession.blankIdx[slot]].toLowerCase(),key=codeSession.keys.find(k=>!k.used&&k.ch===needed);if(!key)return;const el=$(`[data-key="${CSS.escape(key.id)}"]`);if(codeSession.hintLevel>=4){placeKey(key.id,slot);return}el?.classList.add('selected');if(codeSession.hintLevel===3){const target=$(`[data-slot="${slot}"]`);target?.classList.add('hint-target')}setPartner(codeSession.hintLevel===1?'필요한 열쇠 하나가 살짝 반응했어.':codeSession.hintLevel===2?'정답 열쇠를 조금 더 눈여겨봐.':'이 열쇠와 가까운 빈칸을 같이 봐.','hint')}
function checkCodeAnswer(){const built=codeSession.blankIdx.map((_,slot)=>codeSession.keys.find(k=>k.id===codeSession.answers[slot])?.ch||''),need=codeSession.blankIdx.map(i=>codeSession.word.eng[i].toLowerCase());if(built.every((x,i)=>x===need[i])){const elapsed=(Date.now()-codeSession.start)/1000,slow=elapsed>=codeSession.seconds*.7;recordCodeResult(codeSession.wrongAttempts>0?'WRONG':codeSession.hintLevel?'HINT_USED':slow?'SLOW_CORRECT':'CORRECT')}}
function recordCodeResult(type){stopCodeTimer();const w=codeSession.word,attempt={wordId:w.id,type,at:nowISO(),hintLevel:codeSession.hintLevel,wrongAttempts:codeSession.wrongAttempts};const sh=sheet();sh.learningProvenance=sh.learningProvenance||{};sh.learningProvenance.lastActivityAt=attempt.at;sh.learningProvenance.finalSeekAttempts=Number(sh.learningProvenance.finalSeekAttempts||0)+1;S.codeRed.results[w.id]=attempt;S.codeRed.history.push(attempt);w.learningStats=w.learningStats||{};w.learningStats.codeRedAttempts=(w.learningStats.codeRedAttempts||0)+1;if(['WRONG','PASS','TIMEOUT','HINT_USED'].includes(type)){if(!S.codeRed.retrace.includes(w.id))S.codeRed.retrace.push(w.id);if(type==='WRONG')w.wrong=(w.wrong||0)+1;if(type==='PASS')w.pass=(w.pass||0)+1;if(type==='TIMEOUT')w.learningStats.timeout=(w.learningStats.timeout||0)+1;if(type==='HINT_USED')w.hint=(w.hint||0)+1}else{if(type==='SLOW_CORRECT')w.learningStats.slowCorrect=(w.learningStats.slowCorrect||0)+1;S.learning.combo++;S.learning.flow=Math.min(6,S.learning.flow+1)}S.codeRed.index++;markStudy(['CORRECT','SLOW_CORRECT'].includes(type)?5:1);save();if(S.codeRed.index<codeTargets().length)renderCodeRed();else finishCodeRed()}
function startCodeTimer(){const total=codeSession.seconds;codeTimer=setInterval(()=>{const left=Math.max(0,total-(Date.now()-codeSession.start)/1000),pct=Math.round(left/total*100),ring=$('#timeRing'),txt=$('#timeText');if(!ring||!txt)return;ring.style.setProperty('--p',pct);txt.textContent=Math.ceil(left);ring.classList.toggle('warn',pct<=45&&pct>20);ring.classList.toggle('alert',pct<=20);if(left<=0)recordCodeResult('TIMEOUT')},150)}
function stopCodeTimer(){if(codeTimer){clearInterval(codeTimer);codeTimer=null}}
function finishCodeRed(){stopCodeTimer();const currentTargets=codeTargets(),passed=currentTargets.filter(w=>['CORRECT','SLOW_CORRECT'].includes(S.codeRed.results[w.id]?.type)).map(w=>w.id),sh=sheet();if(S.codeRed.retryOnly)S.codeRed.retrace=S.codeRed.retrace.filter(id=>!passed.includes(id));sh.learningProvenance=sh.learningProvenance||{};sh.learningProvenance.lastActivityAt=nowISO();sh.learningProvenance.lastTargetCount=currentTargets.length;sh.learningProvenance.remainingRetraceCount=S.codeRed.retrace.length;if(S.codeRed.retrace.length){sh.status='RETRACE_REQUIRED';save();return renderRetrace()}sh.caseMastery=100;sh.status='TEST_READY';sh.learningProvenance.completedAt=nowISO();sh.learningProvenance.completedWordCount=validWords().length;sh.learningProvenance.finalSeekResultCount=Object.keys(S.codeRed.results||{}).length;S.learning.phase='done';syncSheetToLexicon(sh);save();renderComplete()}
function renderRetrace(){const targets=validWords().filter(w=>S.codeRed.retrace.includes(w.id));$('#view').innerHTML=`<div class="section-title"><h2>SEEK AGAIN</h2><span>Fail → Learn Again → Recall Again</span></div><section class="card tint-leaf"><p>틀린 직후 같은 정답을 즉시 반복하지 않습니다. 뜻·발음·철자를 짧게 다시 본 뒤 해당 단어만 재검증합니다.</p><div class="retrace-list" style="margin-top:13px">${targets.map(w=>`<div class="retrace-item"><div><b>${esc(w.eng)}</b><span>${esc(w.kor)}</span></div><button class="circle-btn speak-retrace" data-word="${esc(w.eng)}" type="button">듣기</button></div>`).join('')}</div><button class="btn danger full" id="retryCode" style="margin-top:13px" type="button">이 단어만 다시 FINAL SEEK</button></section>`;$$('.speak-retrace').forEach(b=>b.onclick=()=>speakWord(b.dataset.word));$('#retryCode').onclick=()=>startCodeRed(true);setPartner('놓쳤다고 끝난 건 아니지. 다시 익힌 뒤 같은 단어만 재검증하자.','note')}
function renderComplete(){const old=selectPastMemoryEvent();if(old)markMemoryEventShown(old);$('#view').innerHTML=`<section class="card tint-leaf" style="text-align:center;padding:25px"><img src="${guideAsset('cheer')}" alt="" style="width:110px;height:110px;object-fit:contain;margin:0 auto 4px"><h1 style="margin:0">학습 준비 완료</h1><p>현재 시험지의 유효 단어를 FINAL SEEK와 SEEK AGAIN까지 확인했어요.</p><div class="grid3" style="margin-top:14px"><div class="status-pill"><b>100%</b><span>Trail Mastery</span></div><div class="status-pill"><b>${S.xp}</b><span>XP</span></div><div class="status-pill"><b>${memoryStrength()}%</b><span>Memory</span></div></div><button class="btn primary full" id="backHome" style="margin-top:14px" type="button">홈으로</button></section>${old?`<div class="section-title"><h2>지난 단어 다시 보기</h2><span>선택적 장기기억 이벤트</span></div><section class="card memory-event"><p>학습 흐름을 막지 않는 작은 확인이야. 건너뛰어도 불이익은 없어.</p><div class="bigword">${esc(old.canonicalSpelling)}</div><p style="text-align:center">${esc(old.sense)}</p><div class="btn-row" style="margin-top:12px"><button class="btn secondary" id="memorySkip" type="button">건너뛰기</button><button class="btn secondary" id="memoryNo" type="button">기억 안 나요</button><button class="btn primary" id="memoryYes" type="button">기억해요</button></div></section>`:''}`;$('#backHome').onclick=()=>{currentTab='home';viewStack=[];render()};if(old){$('#memorySkip').onclick=()=>toast('현재 학습 기록에는 영향이 없어요.');$('#memoryYes').onclick=()=>{old.lastSeen=nowISO();old.memoryStrength=Math.min(100,Number(old.memoryStrength||60)+10);old.nextReviewPriority=Math.max(0,100-old.memoryStrength);save();toast('기억 기록 이상 없음')};$('#memoryNo').onclick=()=>{old.lastSeen=nowISO();old.lastWrong=nowISO();old.memoryStrength=Math.max(10,Number(old.memoryStrength||60)-15);old.nextReviewPriority=Math.max(Number(old.nextReviewPriority||0),100-old.memoryStrength+15);save();toast('다음 복습 우선도를 조금 올렸어요.')}}setPartner('오늘 탐험 완료. 오늘 범위는 여기까지 찾았어.','cheer',true)}
function renderWords(){const ws=validWords();$('#view').innerHTML=`<div class="section-title"><h2>내 단어장</h2><span>${ws.length}개</span></div><section class="card">${ws.length?`<div class="weak-list">${[...ws].sort((a,b)=>weakScore(b)-weakScore(a)).map(w=>`<div class="weak-item"><div><b>${esc(w.eng)}</b><div style="font-size:10px;color:#66736a">${esc(w.kor)}</div></div><span class="badge ${weakScore(w)>=8?'weak':weakScore(w)>0?'mid':'good'}">${weakScore(w)>=8?'약함':weakScore(w)>0?'확인':'안정'}</span></div>`).join('')}</div>`:'<p>아직 단어가 없어요.</p>'}</section>`;setPartner('단어장은 지난 학습의 기록이야. 현재 시험지보다 앞서지는 않아.','note')}
function renderRecords(){const sh=sheet();$('#view').innerHTML=`<div class="section-title"><h2>기록</h2><span>Trail ≠ Memory</span></div><section class="card tint-sky"><div class="metric"><span>Trail Mastery</span><b>${sh.caseMastery||0}%</b></div><div class="metric"><span>Memory Strength</span><b>${memoryStrength()}%</b></div><div class="metric"><span>총 XP</span><b>${S.xp}</b></div><div class="metric"><span>연속 학습</span><b>${S.streak}일</b></div></section><div class="section-title"><h2>최근 학습</h2><span>${APP_REV}</span></div><section class="card">${S.sessions.length?S.sessions.slice(-7).reverse().map(x=>`<div class="metric"><span>${esc(x.date)}</span><b>${x.count}회</b></div>`).join(''):'<p>아직 기록이 없어요.</p>'}</section>`;setPartner('완료한 학습은 완료 상태 그대로야. 장기 기억은 따로 천천히 추적할게.','default')}
function exportData(){const copy=clone(S);delete copy.settings.geminiKey;const blob=new Blob([JSON.stringify(copy,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`HIDE_SEEK_DATA_${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function importData(file){try{const data=JSON.parse(await file.text()),m=migrate(data);if(!Array.isArray(m.sheets)||!m.sheets.length)throw new Error('시험지 데이터가 없어요.');S=m;save();toast('데이터를 불러왔어요.');$('#modalRoot').innerHTML='';render()}catch(e){toast(`불러오기 실패: ${e.message||'파일을 확인해 주세요.'}`)}}
function openSettings(){$('#modalRoot').innerHTML=`<div class="modal-back"><section class="modal"><div class="section-title"><h2>설정</h2><button class="circle-btn" id="closeSettings" type="button">닫기</button></div><div class="setting"><div><label>길잡이 음성</label><small>영어 단어 발음보다 우선하지 않습니다.</small></div><button class="switch ${S.settings.partnerVoice?'on':''}" data-toggle="partnerVoice" type="button"><i></i></button></div><div class="setting"><div><label>Reduced Motion</label><small>과한 움직임을 줄입니다.</small></div><button class="switch ${S.settings.reducedMotion?'on':''}" data-toggle="reducedMotion" type="button"><i></i></button></div><div class="setting"><div><label>긴장 연출 줄이기</label><small>FINAL SEEK 시간을 조금 넉넉하게 제공합니다.</small></div><button class="switch ${S.settings.pressureReduced?'on':''}" data-toggle="pressureReduced" type="button"><i></i></button></div><div class="setting"><div style="width:100%"><label>Gemini API Key</label><small>개인 테스트용 · 이번 브라우저 세션에만 보관. 공개 배포는 서버 프록시 권장.</small><input id="apiKey" class="input" type="password" value="${esc(runtimeApiKey)}" placeholder="API Key"></div></div><div class="setting"><div style="width:100%"><label>Gemini Model</label><input id="apiModel" class="input" value="${esc(S.settings.geminiModel)}"></div></div><div class="btn-row" style="margin-top:13px"><button class="btn secondary" id="exportData" type="button">데이터 내보내기</button><button class="btn secondary" id="importData" type="button">데이터 불러오기</button></div><button class="btn primary full" id="saveSettings" style="margin-top:8px" type="button">설정 저장</button><button class="btn secondary full" id="restartOnboarding" style="margin-top:8px" type="button">프로필/길잡이 다시 설정</button><p style="margin-top:10px">Build ${APP_REV} · Schema ${SCHEMA_VERSION}</p></section></div>`;$('#closeSettings').onclick=()=>$('#modalRoot').innerHTML='';$$('[data-toggle]').forEach(b=>b.onclick=()=>{const k=b.dataset.toggle;S.settings[k]=!S.settings[k];b.classList.toggle('on',S.settings[k]);save()});$('#saveSettings').onclick=()=>{runtimeApiKey=$('#apiKey').value.trim();sessionStorage.setItem(SESSION_API_KEY,runtimeApiKey);S.settings.geminiModel=$('#apiModel').value.trim()||'gemini-2.5-flash';save();$('#modalRoot').innerHTML='';toast('설정을 저장했어요. API Key는 세션에만 유지됩니다.')};$('#restartOnboarding').onclick=()=>{S.onboardingDone=false;S.onboardingStep=0;save();$('#modalRoot').innerHTML='';render()};$('#exportData').onclick=exportData;$('#importData').onclick=()=>$('#importDataInput').click()}
$('#settingsBtn').onclick=openSettings;$('#backBtn').onclick=goBack;$('#partnerVoiceBtn').onclick=()=>partnerSpeak();$('#profileCameraInput').addEventListener('change',e=>profilePicked(e.target.files[0]));$('#profileLibraryInput').addEventListener('change',e=>profilePicked(e.target.files[0]));$('#sheetCameraInput').addEventListener('change',e=>captureFiles(e.target.files,"camera"));$('#sheetLibraryInput').addEventListener('change',e=>captureFiles(e.target.files,"library"));$('#importDataInput').addEventListener('change',e=>importData(e.target.files[0]));$$('.nav-btn').forEach(b=>b.onclick=()=>{viewStack=[];stopCodeTimer();currentTab=b.dataset.tab;render()});if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));save();render();
