#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex');
const cfg=JSON.parse(fs.readFileSync(path.join(root,'assets/visual/hide-living-background.v5.json'),'utf8'));
assert.equal(cfg.visual_id,'TAKY-LAF-HIDE-HOME-MOSSFALL-20260927-A');
assert.equal(sha(cfg.master.path),cfg.master.sha256,'APPROVED_HIDE_MASTER_SHA_MISMATCH');
assert.equal(sha(cfg.motion.path),cfg.motion.sha256,'HIDE_V5_MOTION_SHA_MISMATCH');
const world=fs.readFileSync(path.join(root,'src/v2/mossfall-world.js'),'utf8');
const css=fs.readFileSync(path.join(root,'src/v2/approved-mossfall.css'),'utf8');
const app=fs.readFileSync(path.join(root,'src/v2/app.js'),'utf8');
const sw=fs.readFileSync(path.join(root,'sw-v2.js'),'utf8');
for(const p of [cfg.master.path,cfg.motion.path])assert(sw.includes('./'+p),'OFFLINE_CACHE_MISSING:'+p);
assert(world.includes('id="hideMossfallMotion"'));
assert(world.includes('../../assets/visual/hide_seek_forest_motion_v5.mp4'));
assert(world.includes('prefers-reduced-motion'));
assert(css.includes('data-hide-living-motion="off"'));
assert(app.includes('HideMossfallWorld.syncMotion'));
assert.equal(cfg.runtime.remote_fetch,false);
assert.equal(cfg.gates.main_merge,'HOLD');
assert.equal(cfg.gates.netlify,'HOLD');
console.log(JSON.stringify({gate:'HIDE_LIVING_BACKGROUND_V5',master:'PASS',motion:'PASS',runtimeBinding:'PASS',offlineCache:'PASS',visualSignoff:'OPEN',mainMerge:'HOLD',netlify:'HOLD'},null,2));
