const assert=require('node:assert/strict');
const runtime=require('../hide-crew-live-runtime-v1.js');
const consumer=require('../hide-crew-dialogue-consumer-v1.js');
const c=runtime.legacyCharacter('guide',{utterance:'실제 근거가 있는 말',action:'IDLE',dialogue:'SHORT'});
const plan=runtime.build({sceneId:'global-partner',surface:'global-partner',characters:[c]});
assert.equal(plan.semantic_only,true);assert.equal(plan.generation_allowed,false);assert.equal(plan.asset_selection_allowed,false);assert.equal(c.runtime_eligible,false);
const target={textContent:''};
const doc={querySelector:s=>s===consumer.SURFACES['global-partner']?target:null};
const vm={ok:true,semantic_only:true,app_id:'HIDE_SEEK',scene_id:'global-partner',surface:'global-partner',speaking_order:[c.character_id],characters:[c]};
const out=consumer.apply(vm,doc);assert.equal(out.ok,true);assert.equal(target.textContent,'실제 근거가 있는 말');assert.equal(consumer.changesVisualAsset,false);
console.log(JSON.stringify({gate:'LIVE_CREW_SEMANTIC_RUNTIME',app:'HIDE_SEEK',pass:true},null,2));
